services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    depends_on:
      etcd:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    # command: fastapi dev main.py --host 0.0.0.0 --reload
  redis:
    image: "redis:alpine"
  etcd:
    image: "quay.io/coreos/etcd:v3.5.0"
    container_name: etcd
    ports:
      - "2379:2379"
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 5s
      timeout: 5s
      retries: 5
